import React from "react";
import "./Login.scss";
import commonSetSymbol from "../../../data/commonSetSymbol.svg";
import facebookLogo from "../../../data/facebookIcon.svg";

export default function Login() {
    return (
        <>
            <title>Log in · Terra 2170</title>
            <main className="login-page">
                <img className="set-symbol" src={commonSetSymbol} />
                <h1>Log in to continue</h1>
                <div className="login-buttons">
                <a className="facebook login-button" href="/api/login/facebook"><img src={facebookLogo}/>Log in with Facebook</a>
                </div>
                <p>
                    The only personal information I store is your display name as generated by the service provider you
                    choose to log in with. Your display name is only used to identify yourself to the people in the
                    draft sessions you take part in. By logging in, you give your consent for this information to be
                    used in this way.
                </p>
                <p>
                    If you want me to delete your data (for whatever reason), just let me know. I'll have a proper
                    non-personal email address at some point... [WIP]
                </p>
            </main>
        </>
    );
}
