import React from "react";
import "./Login.scss";
import terraSymbol from "../../../data/terraSymbol.svg";
import googleLogo from "../../../data/googleIcon.svg";
import facebookLogo from "../../../data/facebookIcon.svg";
import githubLogo from "../../../data/githubIcon.svg";

export default function Login() {
    return (
        <>
            <title>Log in · Terra 2170</title>
            <main className="login-page">
                <img className="terra-symbol" src={terraSymbol} />
                <h1>You need to be logged in to continue</h1>
                <div className="login-buttons-container">
                    <a className="google login-button" href="/api/login/google">
                        <img src={googleLogo} />
                        Sign in with Google
                    </a>
                    <a className="facebook login-button" href="/api/login/facebook">
                        <img src={facebookLogo} />
                        Sign in with Facebook
                    </a>
                    <a className="github login-button" href="/api/login/github">
                        <img src={githubLogo} />
                        Sign in with GitHub
                    </a>
                </div>
                <p>
                    The only personal information I store is your display name as generated by the service provider you
                    choose to log in with. Your display name is publically visible. By logging in, you give your consent
                    for this information to be used in this way.
                </p>
                <p>
                    If you want me to delete your data (for whatever reason), just let me know via... whatever channels
                    you have to reach me. I'll have a proper non-personal email address here at some point...
                </p>
            </main>
        </>
    );
}
