DROP TABLE memories;
DROP TABLE cards;
DROP TABLE boosters;
DROP TABLE players;
DROP TABLE drafts;
DROP TABLE draft_statuses;

DELETE FROM users WHERE id = '00';
DELETE FROM users WHERE id = '01';
DELETE FROM users WHERE id = '02';
DELETE FROM users WHERE id = '03';
DELETE FROM users WHERE id = '04';
DELETE FROM users WHERE id = '05';
DELETE FROM users WHERE id = '06';
DELETE FROM users WHERE id = '07';
DELETE FROM users WHERE id = '08';
DELETE FROM users WHERE id = '09';
DELETE FROM users WHERE id = '10';
DELETE FROM users WHERE id = '11';
DELETE FROM users WHERE id = '12';
DELETE FROM users WHERE id = '13';
DELETE FROM users WHERE id = '14';
DELETE FROM users WHERE id = '15';
DELETE FROM users WHERE id = '16';
DELETE FROM users WHERE id = '17';
DELETE FROM users WHERE id = '18';
DELETE FROM users WHERE id = '19';
DELETE FROM users WHERE id = '20';
DELETE FROM users WHERE id = '21';
DELETE FROM users WHERE id = '22';
DELETE FROM users WHERE id = '23';
DELETE FROM users WHERE id = '24';
DELETE FROM users WHERE id = '25';
DELETE FROM users WHERE id = '26';
DELETE FROM users WHERE id = '27';
DELETE FROM users WHERE id = '28';
DELETE FROM users WHERE id = '29';
DELETE FROM users WHERE id = '30';
DELETE FROM users WHERE id = '31';
DELETE FROM users WHERE id = '32';
DELETE FROM users WHERE id = '33';
DELETE FROM users WHERE id = '34';
DELETE FROM users WHERE id = '35';
DELETE FROM users WHERE id = '36';
DELETE FROM users WHERE id = '37';
DELETE FROM users WHERE id = '38';
DELETE FROM users WHERE id = '39';
DELETE FROM users WHERE id = '40';
DELETE FROM users WHERE id = '41';